"""Change schedule_changes reference

Revision ID: 50e2839a1663
Revises: change_vector_to_array
Create Date: 2026-05-01 16:40:52.376355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e2839a1663'
down_revision: Union[str, Sequence[str], None] = 'change_vector_to_array'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_changes', sa.Column('provisional_schedule_slot_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('schedule_changes_task_id_fkey'), 'schedule_changes', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_changes', 'provisional_schedule', ['provisional_schedule_slot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('schedule_changes', 'task_id')
    op.create_foreign_key(None, 'task_statistics_locations', 'task_statistics', ['statistics_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'task_statistics', ['associated_task_statistics_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'tasks', 'task_statistics', ['task_statistics_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'task_statistics_locations', type_='foreignkey')
    op.add_column('schedule_changes', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule_changes', type_='foreignkey')
    op.create_foreign_key(op.f('schedule_changes_task_id_fkey'), 'schedule_changes', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('schedule_changes', 'provisional_schedule_slot_id')
    # ### end Alembic commands ###
