"""initial schema

Revision ID: 54dc77e1dc35
Revises: 
Create Date: 2026-04-11 21:37:02.710970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54dc77e1dc35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.Text(), nullable=False),
    sa.Column('avg_duration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_duration_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('avg_difficulty_delta', sa.Float(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('uncompleted_count', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('category_time_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('locations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasks_statistics',
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('task_name_vector', sa.FLOAT(), nullable=True),
    sa.Column('avg_duration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('avg_duration_delta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_difficulty_delta', sa.Float(), nullable=True),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('uncompleted_count', sa.Integer(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('task_time_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_name')
    )
    op.create_table('category_statistics_locations',
    sa.Column('statistics_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statistics_id'], ['category_statistics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statistics_id', 'location_id')
    )
    op.create_table('task_statistics_locations',
    sa.Column('statistics_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statistics_id'], ['tasks_statistics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('statistics_id', 'location_id')
    )
    op.create_table('tasks',
    sa.Column('task_statistics_id', sa.UUID(), nullable=False),
    sa.Column('associated_task_statistics_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('fixed_time', sa.Boolean(), nullable=False),
    sa.Column('fixed_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['associated_task_statistics_id'], ['tasks_statistics.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_statistics_id'], ['tasks_statistics.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_schedule',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provisional_schedule',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_changes',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('old_slot_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('old_slot_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('new_slot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_categories',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'category_id')
    )
    op.create_table('unscheduled_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unscheduled_tasks')
    op.drop_table('task_categories')
    op.drop_table('schedule_changes')
    op.drop_table('provisional_schedule')
    op.drop_table('main_schedule')
    op.drop_table('tasks')
    op.drop_table('task_statistics_locations')
    op.drop_table('category_statistics_locations')
    op.drop_table('tasks_statistics')
    op.drop_table('locations')
    op.drop_table('category_statistics')
    op.drop_table('categories')
    # ### end Alembic commands ###
